spring:
  datasource:
    url: jdbc:mysql://localhost:3306/morph?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: Age0504!@
    driver-class-name: com.mysql.cj.jdbc.Driver